### ISSUE TITLE
no code

### ISSUE THREAD

**Issue by jayph88** [selfjared1/quickbooks_desktop#3]
no code is present on github.

**Comment by jayph88** [comment]
looks like spam project

**Comment by selfjared1** [comment]
@jayph88 There is code inside of the repository and the code works.  Have you dug down into the folders to look at any of it?  If you have questions on how to use the code you can also look at the tests here: https://github.com/selfjared1/quickbooks_desktop/blob/master/src/quickbooks_desktop/tests/test_session_manager.py
